eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0

spring:
  application:
    name:
      ms-orders
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
  config:
    import: "optional:configserver:http://localhost/7000"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_III
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true