spring:
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: user
      password: user
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge_III
    username: postgres
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true


jwt:
  secret: ${JWT_SECRET:my-secret-key}

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


